import json
import os
import subprocess
import urllib.request
import hashlib

META_URL = "https://kamori.goats.dev/Dalamud/Release/Meta"
BRANCH_FILE = "dalamud-branches.json"


def runtime_ver_to_nix_sdk(runtime_version):
    parts = runtime_version.split(".")
    major, minor = parts[0], parts[1]
    if not (major.isdigit() and minor.isdigit()):
        raise ValueError(f"Unsupported .NET runtime version format: {runtime_version}")
    return f"sdk_{major}_{minor}"


def generate_branch(branch, info):
    runtimeVersion = info["runtimeVersion"]
    if runtimeVersion is None:
        print(f"Skipping branch '{branch}' as it does not have a runtime version")
        return None
    downloadUrl = info["downloadUrl"]
    if downloadUrl is None:
        print(f"Skipping branch '{branch}' as it does not have a download url")
        return None
    version = info["assemblyVersion"]
    if version is None:
        print(f"Skipping branch '{branch}' as it does not have a version number")
        return None

    print(
        f"Processing branch '{branch}' (version {version}, runtime {runtimeVersion})"
    )
    result = subprocess.check_output(
        [
            "nix",
            "store",
            "prefetch-file",
            "--unpack",
            "--hash-type",
            "sha256",
            "--json",
            downloadUrl,
        ],
        stderr=subprocess.DEVNULL,
        text=True,
    )

    return branch, {
        "version": version,
        "runtimeVersion": runtimeVersion,
        "downloadUrl": downloadUrl,
        "nix": {
            "hash": json.loads(result)["hash"],
            "dotnetSdkVersion": runtime_ver_to_nix_sdk(runtimeVersion),
        },
    }


# Fetch remote branch metadata.
print(f"Fetching release information from {META_URL}")
with urllib.request.urlopen(META_URL) as response:
    meta = json.load(response)
    checksum = hashlib.sha256(
        json.dumps(meta, indent=None, sort_keys=True, ensure_ascii=True).encode("utf-8")
    ).hexdigest()

# Check if anything changed since last run.
if os.path.exists(BRANCH_FILE):
    try:
        with open(BRANCH_FILE, "r") as f:
            existing_checksum = json.load(f).get("_generated", {}).get("checksum")
            if existing_checksum == checksum:
                print("No changes found since last update")
                exit(0)
    except (json.JSONDecodeError, KeyError):
        pass

# Update local branch data.
branches = dict(
    result
    for branch, info in meta.items()
    if (result := generate_branch(branch, info)) is not None
)
with open(BRANCH_FILE, "w") as f:
    json.dump(
        {
            "_generated": {
                "note": "This file is autogenerated, do not edit manually.",
                "source": META_URL,
                "checksum": checksum,
            },
            "branches": branches,
        },
        f,
        indent=2,
    )
print(f"Updated {BRANCH_FILE} ({checksum})")
